### ISSUE TITLE
HW1 authentication 관련 질문

### ISSUE THREAD

**Issue by BaekGeunYoung** [snu-sf-class/swpp201901#12]
주의사항에 meeting/id url에는 회의실을 예약한 유저만 접근할 수 있다고 되어있는데, 이 url에는 단순히 detail을 띄우는 GET요청도 할 수 없는 건가요? 아니면 GET은 가능한데 PUT과 DELETE만 못하게 하는건가요?

**Comment by minkiminki** [comment]
GET도 막히도록 구현하시면 됩니다.
