### ISSUE TITLE
ImportError: cannot import name include

### ISSUE THREAD

**Issue by uyw4687** [snu-sf-class/swpp201901#14]
quickstart부터 시작해보려고 하고 있는데
(https://www.django-rest-framework.org/tutorial/quickstart/)
python manage.py runserver
이걸 하면 전에는 됐었는데
지금은
~~tutorial/tutorial/tutorial/urls.py", line 19, in <module>
from django.urls import include, path
  ImportError: cannot import name include
오류가 뜹니다.
어디서 잘못된 걸까요?

파이썬 버전 문제일 것 같지는 않지만 파이썬 업데이트도 했었는데
virtualenv 안에서는 어차피 python 2 버전으로 실행되는 것 같고
tutorial 폴더가 저렇게 많은 게 정상인지 어디서 잘못된 건지 모르겠어요

**Comment by KimHeekon** [comment]
python2 에서는 django도 옛날 버전으로 돌아가서 django.urls 안에 import와 path가 들어있지 않아 나는 에러 같습니다.
올바른 해결책인지는 모르겠으나 저는 싹 지우고 pip -> pip3, python->python3으로 바꿔서 따라하니 해결됐습니다.

**Comment by uyw4687** [comment]
pip3 설치하고 하니까 되는 것 같아요!! 감사합니다~
