### ISSUE TITLE
HW1 GET 데이터 출력 순서

### ISSUE THREAD

**Issue by lionminhu** [snu-sf-class/swpp201901#18]
과제 PDF에는 `GET meetings/<int:pk>` 형식이 이런 식으로 나와야 한다고 되어있습니다.
![img](https://i.imgur.com/6zXK6iD.png)

현재 제가 구현한 것에서는 `httpie`를 이용해서 GET을 하면 이 순서대로 표시되지 않고, element가 key 값에 대해 정렬되어 나옵니다.
```bash
(env) root@doota:~/mwlee/ppsw-assignments/hw1/main/meetings# http -a admin1:qwerty1234 GET http://127.0.0.1:8000/meetings/30/
HTTP/1.1 200 OK
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
Content-Length: 126
Content-Type: application/json
Date: Sat, 23 Mar 2019 13:18:15 GMT
Server: WSGIServer/0.2 CPython/3.6.8
Vary: Accept, Cookie
X-Frame-Options: SAMEORIGIN

{
    "created": "2019-03-23T00:15:20.840712Z",
    "id": 30,
    "sinceWhen": "2020-01-02T11:11:00Z",
    "tilWhen": "2020-01-03T11:20:00Z",
    "user": 1
}
```

하지만 브라우저에서 (`admin1` 계정으로 로그인 한 후) `http://127.0.0.1:8000/meetings/30/`로 접속하면 PDF에 나온 순서대로 표시됩니다:
![img2](https://i.imgur.com/zocHBag.png)

혹시 `httpie`로 요청하는 경우에도 PDF에 나온 순서를 그대로 따라야 하나요?

**Comment by ldm2468** [comment]
https://github.com/jakubroztocil/httpie/issues/427
이 이슈를 보시면 httpie가 자체적으로 key를 알파벳 순서로 재정렬하는 것 같네요.
서버 설정과는 관계가 없어보입니다.
Workaround로는 위의 이슈에 나와있듯 httpie에 `--pretty=colors` 설정을 추가하면 원래 json이 그대로 출력되는 것 같네요.

**Comment by lionminhu** [comment]
그렇다면 과제 코드에서 딱히 고칠 수 있는 부분은 아닌 것 같군요. 감사합니다.

**Comment by Sung-HwanLee** [comment]
별개로, 채점시 json field의 출력 순서는 별로 중요하지 않습니다.
