### ISSUE TITLE
아직 조 못 만드신 분 계신가요?

### ISSUE THREAD

**Issue by hyunsama** [snu-sf-class/swpp201901#2]
아직 조를 못 만드신 분들 중 저와 하실 분은 댓글 남겨주세요!

**Comment by sally20921** [comment]
아직 조가 없습니다! 같이 하고 싶습니다.

**Comment by hyunsama** [comment]
넵 제 카카오ID는 hyunsamajung입니다! 같이 하고 싶으신 분들은 카톡주셔도 되고 댓글로 남겨주세요~
