### ISSUE TITLE
[HW2]login

### ISSUE THREAD

**Issue by uyw4687** [snu-sf-class/swpp201901#27]
로그인 페이지를 새로 만드는 건가요?
django에서 사용했던 로그인페이지는 사용할 수 없나요?

백엔드랑 프론트엔드 관계가 잘 이해가 가지 않는데 프론트엔드에서 GET POST PUT DELETE를 백엔드로 보내는 형태로 서비스가 이루어지나요? 그런 request를 Redux-saga로 보내는 건가요?

과제는 ARc로 하면 되는 거죠?

감사합니다

**Comment by minkiminki** [comment]
> 로그인 페이지를 새로 만드는 건가요?
django에서 사용했던 로그인페이지는 사용할 수 없나요?

로그인 페이지는 새로 만드셔야 합니다. 모든 사용자에게 보일 페이지는 React를 이용하여 만드셔야 합니다.

> 백엔드랑 프론트엔드 관계가 잘 이해가 가지 않는데 프론트엔드에서 GET POST PUT DELETE를 백엔드로 보내는 형태로 서비스가 이루어지나요? 그런 request를 Redux-saga로 보내는 건가요?

네. frontend에서 request를 백엔드 서버에 보내는 식으로 이뤄지고, 그 부분은 Redux-saga를 이용하여 구현하시면 됩니다.

> 과제는 ARc로 하면 되는 거죠?

React, Redux, Redux-saga는 필수고 ARc는 필수는 아니지만 ARc를 사용하면 편하실 것입니다.

**Comment by uyw4687** [comment]
혹시 todolist_example 실행해보려면 backend에서 python manage.py runserver
frontend에서 npm start 해서 둘 다 켜서 확인하는 건가요? hw2할 때도 동일한가요?

**Comment by minkiminki** [comment]
@uyw4687 네. 맞습니다. 둘 다 실행하셔야 합니다.

**Comment by uyw4687** [comment]
감사합니다. 혹시 alice, bob 사용자를 backend에서 등록해주는 것 맞죠? 그럼 migration 후 backend db에 사용자가 있는 상태로 AWS에 올려주면 되는 건가요?

**Comment by minkiminki** [comment]
@uyw4687 네. 그렇습니다.
