### ISSUE TITLE
예약 추가 관련 질문

### ISSUE THREAD

**Issue by BaekGeunYoung** [snu-sf-class/swpp201901#31]
HW2 관련 질문입니다.
사용자 로그인이 되어 있지 않을 경우 예약 추가와 관련한 컴포넌트는 보여주지 않아야 하는건가요?
아니면 컴포넌트는 보여주되, 포스트 요청을 했을 때 bad request를 띄워야 하는건가요?

**Comment by minkiminki** [comment]
어떻게 구현하셔도 상관 없습니다. 문서에 명확히 적혀 있지 않은 부분은 마음대로 구현하시면 됩니다.
