### ISSUE TITLE
예약 시간 입력 관련 질문

### ISSUE THREAD

**Issue by sjho** [snu-sf-class/swpp201901#32]
예약 입력 날짜는 그냥 일반 텍스트로 입력하게 하면 되는 건가요?

**Comment by minkiminki** [comment]
예년에는 https://www.npmjs.com/package/react-datepicker 같은 라이브러리를 쓰신 분도 계셨고 일반 텍스트로(이 경우 어떤 포맷으로 입력해야 하는지 예시를 적어주시기 바랍니다) 입력을 받으신 분도 계셨습니다. 어느쪽이든 상관은 없습니다.
